server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;
    
    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.html$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
    }

    # Solo imágenes con caché
    location ~* \.(?:gif|jpe?g|png|ico|svg|webp)$ {
        expires 30d;
        access_log off;
        log_not_found off;
    }

    error_page 404 /index.html;

}
