services:
  api-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_dev
    environment:
      - ENV=${ENV}
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    env_file:
      - backend/.env.${ENV}
    networks:
      - krear3d
    volumes:
      - ./backend:/application
      - ./shared_uploads:/shared_uploads
    ports:
      - "${API_PORT}:${API_PORT}"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${API_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 5
    platform: linux/amd64
    restart: always

  redis-dev:
    image: redis:latest
    container_name: redis_dev
    networks:
      - krear3d
    restart: always
    command: redis-server --requirepass "150723"

  #support:
  #  build:
  #    context: ./support
  #    dockerfile: Dockerfile
  #  container_name: support
  #  networks:
  #    - krear3d
  #  volumes:
  #    - ./support:/usr/share/nginx/html
  #  ports:
  #   - 8003:80
  #   - 4003:443
  #  restart: always

  intranet-dev:
    build:
      context: ./intranet
      dockerfile: Dockerfile
    container_name: intranet_dev
    networks:
      - krear3d
    volumes:
      - ./intranet:/usr/share/nginx/html
      - ./shared_uploads:/usr/share/nginx/html/static/images/uploads
    ports:
      - 7010:80
      - 3010:443
    restart: always

networks:
  krear3d:
    driver: bridge

volumes:
  shared_uploads:
